# Generated by Django 5.0.3 on 2024-03-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('snacks', 'Салаты и Закуски'), ('first_dishes', 'Супы'), ('main_dishes', 'Второе'), ('baking', 'Хлеб и Выпечка'), ('desserts', 'Десерты'), ('drinks', 'Безалкогольные напитки'), ('alco', 'пойло')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
