# Generated by Django 5.0.6 on 2024-05-23 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('snacks', 'Салаты и Закуски'), ('first_dishes', 'Супы'), ('main_dishes', 'Второе'), ('baking', 'Хлеб и Выпечка'), ('desserts', 'Десерты'), ('drinks', 'Безалкогольные напитки'), ('alco', 'Пойло'), ('not_set', 'Soon!')], default='alco', max_length=20)),
                ('default_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Soon!', max_length=100)),
                ('review', models.TextField(db_comment='отсекаем на 100 знаков', default='Soon!')),
                ('algorythm', models.TextField(default='Soon!', max_length=1000)),
                ('time_estimate', models.IntegerField(default=5)),
                ('preview', models.ImageField(default=None, null=True, upload_to='dishes')),
                ('author', models.CharField(default='Some Cook!', max_length=100)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cook_house.categoryrecipe')),
            ],
        ),
    ]
