# Generated by Django 5.0.3 on 2024-03-07 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrecipe',
            name='default_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='algorythm',
            field=models.TextField(default='Soon!', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='Some Cook!', max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default='not_set', on_delete=django.db.models.deletion.DO_NOTHING, to='cook_house.categoryrecipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(null=True, upload_to='dishes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='review',
            field=models.TextField(db_comment='отсекаем на 100 знаков', default='Soon!'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_estimate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Soon!', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryrecipe',
            name='title',
            field=models.CharField(choices=[('snacks', 'Салаты и Закуски'), ('first_dishes', 'Супы'), ('main_dishes', 'Второе'), ('baking', 'Хлеб и Выпечка'), ('desserts', 'Десерты'), ('drinks', 'Безалкогольные напитки'), ('alco', 'Пойло'), ('not_set', 'Soon!')], max_length=20),
        ),
    ]
