# Generated by Django 5.0.6 on 2024-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(default=None, null=True, upload_to='uploads/'),
        ),
    ]
