# Generated by Django 5.0.6 on 2024-07-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_house', '0004_alter_recipe_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(upload_to=''),
        ),
    ]
